cmd: dtimg: Report invalid index argument
Being user-friendly is paramount to make any product likeable and
easy to use. Hence, instead of [1], print [2].

[1] dtimg start 0x48000000 not-a-number myvar
Error: Wrong index

[2] dtimg start 0x48000000 not-a-number myvar
Error: Wrong index 'not-a-number'

Signed-off-by: Eugeniu Rosca <erosca@de.adit-jv.com>